title: Sea Sensors
description: Sea Sensors is an acoustic data project that collects underwater blast data to help provide quantitative spatial information on the incidence of the problem over time, that will enable targeted enforcement.
author: sensors.AFRICA by Code for Africa

url: https://seasensors.africa
enforce_ssl: seasensors.africa

tw_url: https://twitter.com/hashtag/seasensors?src=hash
fb_url: https://www.facebook.com/hashtag/AcousticOceans
gh_url: https://github.com/CodeForAfricaLabs/sensors.AFRICA
md_url: https://medium.com/code-for-africa/tagged/innovateafrica
ig_url: https://www.instagram.com/p/BjfrFfmlGKJ/

google_analytics: UA-44795600-44
